import type { Product } from '../types/catalog';
import { getSupabaseClient, hasSupabaseConfiguration } from './supabase';
import type { TaxonomyCategory, TaxonomyProduct } from './product-taxonomy';
import { normaliseProductDetailContent } from '../types/product-detail-content';
type Row={id:string;slug:string;name:string;description:string;detail_content?:unknown;price:number|string;category:string;category_id:string|null;theme_slugs:string[];display_order:number;image_tone:string;image_path:string|null;product_images?:Array<{path:string;display_order:number}>;product_finishes?:Array<{name:string;product_colours?:{id:string;name:string;hex_code:string}|Array<{id:string;name:string;hex_code:string}>|null}>};
type CategoryRow={id:string;name:string;parent_id:string|null;depth:1|2|3;display_order:number;is_active:boolean};
export type PublicProduct = Product & TaxonomyProduct & { themeSlugs: string[]; imageUrl: string | null; galleryImageUrls: string[] };
export type PublicCatalogue = { products: PublicProduct[]; categories: TaxonomyCategory[] };
function productAssetUrl(path: string | null) { return path ? getSupabaseClient().storage.from('product-assets').getPublicUrl(path).data.publicUrl : null; }
export function mapPublicProductRow(row:Row):PublicProduct{const galleryImageUrls=(row.product_images??[]).sort((a,b)=>a.display_order-b.display_order).map((image)=>productAssetUrl(image.path)).filter((url):url is string=>Boolean(url));const colours=(row.product_finishes??[]).flatMap((finish)=>{const colour=Array.isArray(finish.product_colours)?finish.product_colours[0]:finish.product_colours;return colour?[{id:colour.id,name:colour.name,hexCode:colour.hex_code}]:[]});return{id:row.id,slug:row.slug,name:row.name,description:row.description,detailContent:normaliseProductDetailContent(row.detail_content),price:Number(row.price),category:row.category as Product['category'],categoryId:row.category_id,themeSlugs:row.theme_slugs,displayOrder:row.display_order,isActive:true,imageTone:row.image_tone,imageUrl:productAssetUrl(row.image_path),galleryImageUrls,finishes:(row.product_finishes??[]).map(x=>x.name),colours}}
function mapPublicCategoryRow(row:CategoryRow):TaxonomyCategory{return{id:row.id,name:row.name,parentId:row.parent_id,depth:row.depth,displayOrder:row.display_order,isActive:row.is_active};}
export async function listPublicCatalogue():Promise<PublicCatalogue>{if(!hasSupabaseConfiguration())return{products:[],categories:[]};const client=getSupabaseClient();const[productsResult,categoriesResult]=await Promise.all([client.from('products').select('id, slug, name, description, detail_content, price, category, category_id, theme_slugs, display_order, image_tone, image_path, product_images(path, display_order), product_finishes(name, product_colours(id, name, hex_code))').eq('is_active',true).order('display_order'),client.from('product_categories').select('id, name, parent_id, depth, display_order, is_active').eq('is_active',true).order('display_order')]);if(productsResult.error||categoriesResult.error)throw new Error('Unable to load public catalogue.');return{products:(productsResult.data??[]).map(x=>mapPublicProductRow(x as Row)),categories:(categoriesResult.data??[]).map(x=>mapPublicCategoryRow(x as CategoryRow))};}
export async function listActiveProducts():Promise<Product[]>{return (await listPublicCatalogue()).products;}
