import { FormEvent, useMemo, useState } from 'react';
import { updateScheduleAmount, updateSchedulePercent, validatePaymentPlan, type PaymentPlanDraft } from '../../lib/payment-plan';
type EditablePaymentPlanInstalment = PaymentPlanDraft & { status?: 'draft' | 'issued' | 'paid' | 'overdue' };

export function PaymentPlanEditor({ quoteTotal, instalments, onSave, onSync }: {
  quoteTotal: number;
  instalments: EditablePaymentPlanInstalment[];
  onSave: (instalments: PaymentPlanDraft[]) => Promise<PaymentPlanDraft[]>;
  onSync: () => Promise<void> | void;
}) {
  const [lines, setLines] = useState(instalments);
  const [savedLines, setSavedLines] = useState('');
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const validation = useMemo(() => validatePaymentPlan(lines, quoteTotal), [lines, quoteTotal]);
  const update = (index: number, value: Partial<PaymentPlanDraft>) => setLines((current) => current.map((line, currentIndex) => currentIndex === index ? { ...line, ...value } : line));
  const updatePercent = (index: number, percentage: number) => { try { setLines((current) => updateSchedulePercent(current, index, percentage, quoteTotal)); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update instalment.'); } };
  const updateAmount = (index: number, amount: number) => { try { setLines((current) => updateScheduleAmount(current, index, amount, quoteTotal)); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update instalment.'); } };
  const move = (index: number, offset: number) => setLines((current) => { const next = [...current]; const target = index + offset; if (target < 0 || target >= next.length) return current; [next[index], next[target]] = [next[target], next[index]]; return next; });
  const save = async (event: FormEvent) => { event.preventDefault(); if (!validation.valid) { setError(validation.message); return; } setSaving(true); setError(''); try { const saved = await onSave(lines); setLines(saved); setSavedLines(JSON.stringify(saved)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save the payment schedule.'); } finally { setSaving(false); } };
  const isSaved = savedLines === JSON.stringify(lines);
  const sync = async () => { setSaving(true); setError(''); try { await onSync(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to synchronise invoice drafts.'); } finally { setSaving(false); } };
  return <form className="payment-plan-editor" onSubmit={(event) => void save(event)}><div><p className="eyebrow">Payment plan</p><h2>Schedule instalments</h2><p>Confirmed quote total: <b>${quoteTotal.toLocaleString('en-AU', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</b></p></div>
    <div className="payment-plan-editor__lines">{lines.map((line, index) => <fieldset disabled={line.status === 'issued' || line.status === 'paid' || line.status === 'overdue'} className="payment-plan-editor__line" key={line.id ?? `${index}-${line.label}`}><label>Description<input aria-label={`Instalment ${index + 1} description`} value={line.label} onChange={(event) => update(index, { label: event.target.value })} /></label><label>Percent<input aria-label={`Instalment ${index + 1} percent`} min="0" step="0.01" type="number" value={line.percentage || ''} onChange={(event) => updatePercent(index, Number(event.target.value))} /></label><label>Amount<input aria-label={`Instalment ${index + 1} amount`} min="0" step="0.01" type="number" value={line.amount || ''} onChange={(event) => updateAmount(index, Number(event.target.value))} /></label><label>Due date<input aria-label={`Instalment ${index + 1} due date`} type="date" value={line.dueOn} onChange={(event) => update(index, { dueOn: event.target.value })} /></label><label>Internal note<input aria-label={`Instalment ${index + 1} internal note`} value={line.internalNote} onChange={(event) => update(index, { internalNote: event.target.value })} /></label><div className="payment-plan-editor__tools"><button aria-label={`Move instalment ${index + 1} up`} className="admin-text-button" disabled={line.status === 'issued' || line.status === 'paid' || line.status === 'overdue' || index === 0 || lines[index - 1]?.status === 'issued' || lines[index - 1]?.status === 'paid' || lines[index - 1]?.status === 'overdue'} onClick={() => move(index, -1)} type="button">↑</button><button aria-label={`Move instalment ${index + 1} down`} className="admin-text-button" disabled={line.status === 'issued' || line.status === 'paid' || line.status === 'overdue' || index === lines.length - 1 || lines[index + 1]?.status === 'issued' || lines[index + 1]?.status === 'paid' || lines[index + 1]?.status === 'overdue'} onClick={() => move(index, 1)} type="button">↓</button><button className="admin-text-button admin-text-button--danger" onClick={() => setLines((current) => current.filter((_, currentIndex) => currentIndex !== index))} type="button">Remove</button></div></fieldset>)}</div>
    <button className="admin-secondary-button" type="button" onClick={() => setLines((current) => [...current, { label: '', percentage: 0, amount: 0, dueOn: '', internalNote: '' }])}>Add instalment</button>
    <p className="payment-plan-editor__total">Plan total <b>${lines.reduce((sum, line) => sum + (Number.isFinite(line.amount) ? line.amount : 0), 0).toLocaleString('en-AU', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</b></p>{!validation.valid && <p className="error" role="alert">{validation.message}</p>}{error && <p className="error" role="alert">{error}</p>}
    <div className="payment-plan-editor__actions"><button className="button" disabled={saving} type="submit">{saving ? 'Saving…' : 'Save payment schedule'}</button><button className="admin-secondary-button" disabled={!validation.valid || !isSaved || saving} onClick={() => void sync()} type="button">Sync invoice drafts</button></div>
  </form>;
}