import { FormEvent, useEffect, useState } from 'react';
import { createManagedProductColour, listManagedProductColours, type ProductSaveInput } from '../../lib/admin-api';
import { slugify } from '../../lib/slug';
import type { ManagedProduct, ManagedProductCategory, ManagedStyleRange, ProductColour } from '../../types/domain';
import { emptyProductDetailContent, normaliseProductDetailContent } from '../../types/product-detail-content';
import { ProductDetailContentFields } from './ProductDetailContentFields';

type ProductFormProps = { categories?: ManagedProductCategory[]; styleRanges?: ManagedStyleRange[]; colours?: ProductColour[]; initialValue?: ManagedProduct; onSave: (input: ProductSaveInput) => Promise<void>; onCreateColour?: (input: Omit<ProductColour, 'id'>) => Promise<ProductColour>; onCancel?: () => void };

function valuesFrom(product?: ManagedProduct): ProductSaveInput {
  return { id: product?.id, name: product?.name ?? '', slug: product?.slug ?? '', description: product?.description ?? '', detailContent: normaliseProductDetailContent(product?.detailContent ?? emptyProductDetailContent()), price: product?.price ?? 0, category: product?.category ?? '', subcategory: product?.subcategory ?? '', categoryId: product?.categoryId ?? null, categoryPath: product?.categoryPath ?? [], themeSlugs: product?.themeSlugs ?? [], finishes: product?.finishes ?? [], colours: product?.colours ?? [], imagePath: product?.imagePath ?? null, isActive: product?.isActive ?? true, displayOrder: product?.displayOrder ?? 0, imageFile: undefined };
}

export function ProductForm({ categories = [], styleRanges = [], colours, initialValue, onCancel, onCreateColour = createManagedProductColour, onSave }: ProductFormProps) {
  const [value, setValue] = useState<ProductSaveInput>(() => valuesFrom(initialValue));
  const [availableColours, setAvailableColours] = useState<ProductColour[]>(colours ?? []);
  const [creatingColour, setCreatingColour] = useState(false); const [colourName, setColourName] = useState(''); const [hexCode, setHexCode] = useState(''); const [colourError, setColourError] = useState(''); const [colourSaving, setColourSaving] = useState(false);
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { const next = valuesFrom(initialValue); setValue(next); setError(''); }, [initialValue]);
  useEffect(() => { if (colours) { setAvailableColours(colours); return; } let active = true; void listManagedProductColours().then((next) => { if (active) setAvailableColours(next); }).catch(() => undefined); return () => { active = false; }; }, [colours]);
  const update = <K extends keyof ProductSaveInput>(key: K, next: ProductSaveInput[K]) => setValue((current) => ({ ...current, [key]: next }));
  const updateName = (name: string) => setValue((current) => ({ ...current, name, slug: slugify(name) }));
  const toggleRange = (slug: string) => update('themeSlugs', value.themeSlugs.includes(slug) ? value.themeSlugs.filter((range) => range !== slug) : [...value.themeSlugs, slug]);
  const activeCategories = categories.filter((category) => category.isActive); const primary = activeCategories.filter((category) => category.depth === 1); const selectedPrimary = primary.find((category) => category.name === value.category); const secondary = activeCategories.filter((category) => category.depth === 2 && category.parentId === selectedPrimary?.id); const secondaryName = value.subcategory.split(' / ')[0]; const selectedSecondary = secondary.find((category) => category.name === secondaryName); const tertiary = activeCategories.filter((category) => category.depth === 3 && category.parentId === selectedSecondary?.id);
  const selectPrimary = (id: string) => { const category = primary.find((item) => item.id === id); if (category) setValue((current) => ({ ...current, category: category.name, subcategory: '', categoryId: null, categoryPath: [category.name] })); };
  const selectSecondary = (id: string) => { const category = secondary.find((item) => item.id === id); if (category && selectedPrimary) setValue((current) => ({ ...current, subcategory: category.name, categoryId: null, categoryPath: [selectedPrimary.name, category.name] })); };
  const selectTertiary = (id: string) => { const category = tertiary.find((item) => item.id === id); if (category && selectedPrimary && selectedSecondary) setValue((current) => ({ ...current, subcategory: `${selectedSecondary.name} / ${category.name}`, categoryId: category.id, categoryPath: [selectedPrimary.name, selectedSecondary.name, category.name] })); };
  const selectColour = (id: string) => { if (id === '__create_colour__') { setCreatingColour(true); setColourError(''); return; } const colour = availableColours.find((item) => item.id === id); if (colour && !value.colours?.some((item) => item.id === colour.id)) update('colours', [...(value.colours ?? []), colour]); };
  const removeColour = (id: string) => update('colours', (value.colours ?? []).filter((colour) => colour.id !== id));
  async function createColour(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setColourSaving(true); setColourError(''); try { const colour = await onCreateColour({ name: colourName, hexCode }); setAvailableColours((current) => [...current, colour].sort((left, right) => left.name.localeCompare(right.name))); update('colours', [...(value.colours ?? []), colour]); setCreatingColour(false); setColourName(''); setHexCode(''); } catch (createError) { setColourError(createError instanceof Error ? createError.message : 'Unable to create colour.'); } finally { setColourSaving(false); } }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const name = value.name.trim(); const slug = value.slug.trim().toLowerCase(); const description = value.description.trim();
    if (!name || !description) { setError('Name and description are required.'); return; }
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) { setError('Use a URL-safe slug with lowercase letters, numbers and hyphens.'); return; }
    if (!Number.isFinite(value.price) || value.price < 0) { setError('Enter a valid non-negative price.'); return; }
    if (!value.themeSlugs.length) { setError('Choose at least one product range.'); return; }
    if (categories.length && !value.categoryId) { setError('Choose a sub-subcategory for this product.'); return; }
    setSaving(true); setError(''); try { await onSave({ ...value, name, slug, description, finishes: (value.colours ?? []).map((colour) => colour.name) }); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : 'Unable to save product.'); } finally { setSaving(false); }
  }
  return <><form className="product-form" onSubmit={(event) => void submit(event)}><div className="product-form__heading"><div><p className="eyebrow">{value.id ? 'Edit product' : 'New product'}</p><h2>{value.id ? value.name || 'Product details' : 'Add a product'}</h2></div>{onCancel && <button className="admin-text-button" onClick={onCancel} type="button">Close</button>}</div><div className="product-form__grid">
    <label>Name<input aria-label="Product name" onChange={(event) => updateName(event.target.value)} value={value.name} /></label><label>URL slug<input aria-label="Product slug" readOnly value={value.slug} /></label>
    <label className="product-form__full">Description<textarea aria-label="Product description" onChange={(event) => update('description', event.target.value)} value={value.description} /></label><label>Price (AUD)<input aria-label="Product price" min="0" onChange={(event) => update('price', Number(event.target.value))} step="0.01" type="number" value={value.price} /></label><label>Display order<input aria-label="Product display order" disabled={!value.id} min="1" onChange={(event) => update('displayOrder', Number(event.target.value))} step="1" type="number" value={value.id ? value.displayOrder : ''} /></label>
    <ProductDetailContentFields onChange={(detailContent) => update('detailContent', detailContent)} value={value.detailContent} />
    <label>L1 Category<select aria-label="L1 Category" onChange={(event) => selectPrimary(event.target.value)} value={selectedPrimary?.id ?? ''}><option value="">Select L1 category</option>{primary.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>L2 Category<select aria-label="L2 Category" disabled={!selectedPrimary} onChange={(event) => selectSecondary(event.target.value)} value={selectedSecondary?.id ?? ''}><option value="">Select L2 category</option>{secondary.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>L3 Category<select aria-label="L3 Category" disabled={!selectedSecondary} onChange={(event) => selectTertiary(event.target.value)} value={value.categoryId ?? ''}><option value="">Select L3 category</option>{tertiary.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="product-form__full">Colours<select aria-label="Product colours" onChange={(event) => selectColour(event.target.value)} value=""><option value="">Select a colour</option>{availableColours.map((colour) => <option key={colour.id} value={colour.id}>{colour.name} · {colour.hexCode}</option>)}<option value="__create_colour__">Create a new colour</option></select>{Boolean(value.colours?.length) && <div className="product-colour-list">{value.colours?.map((colour) => <span key={colour.id}><i aria-hidden="true" style={{ backgroundColor: colour.hexCode }} />{colour.name}<button aria-label={`Remove ${colour.name}`} onClick={() => removeColour(colour.id)} type="button">×</button></span>)}</div>}</label>
    <fieldset className="product-form__full"><legend>Product ranges</legend><div className="product-form__checks">{styleRanges.filter((range) => range.isActive).map((range) => <label key={range.id}><input checked={value.themeSlugs.includes(range.slug)} onChange={() => toggleRange(range.slug)} type="checkbox" />{range.name}</label>)}{!styleRanges.filter((range) => range.isActive).length && <p>No active product ranges. Create one in Content first.</p>}</div></fieldset>
    <label className="product-form__full">Product image<input accept="image/jpeg,image/png,image/webp" aria-label="Product image" onChange={(event) => update('imageFile', event.target.files?.[0])} type="file" /><small>{value.imagePath ? 'A product image is currently saved. Choose a new file only to replace it.' : 'JPG, PNG or WebP · optional'}</small></label><label className="product-form__toggle"><input aria-label="Visible on public website" checked={value.isActive} onChange={(event) => update('isActive', event.target.checked)} type="checkbox" />Visible on public website</label>
  </div>{error && <p className="error" role="alert">{error}</p>}<button className="button" disabled={saving} type="submit">{saving ? 'Saving…' : 'Save product'}</button></form>{creatingColour && <div className="colour-create-dialog__backdrop"><section aria-label="Create a new colour" className="colour-create-dialog" role="dialog"><form onSubmit={(event) => void createColour(event)}><p className="eyebrow">Colour library</p><h2>Create a new colour</h2><label>Colour name<input aria-label="Colour name" onChange={(event) => setColourName(event.target.value)} value={colourName} /></label><label>HEX colour code<input aria-label="HEX colour code" onChange={(event) => setHexCode(event.target.value)} placeholder="#000000" value={hexCode} /></label>{colourError && <p className="error" role="alert">{colourError}</p>}<div><button className="admin-text-button" onClick={() => setCreatingColour(false)} type="button">Cancel</button><button className="button" disabled={colourSaving} type="submit">{colourSaving ? 'Creating…' : 'Create colour'}</button></div></form></section></div>}</>;
}
