import { useCallback, useEffect, useState } from 'react';
import { ProductForm } from '../../components/admin/ProductForm';
import { ProductTable } from '../../components/admin/ProductTable';
import { QuoteBasedProductTable } from '../../components/admin/QuoteBasedProductTable';
import { CabinetryProductManager } from '../../components/admin/CabinetryProductManager';
import { AdminModal } from '../../components/admin/AdminModal';
import { archiveProduct, deleteProduct, listManagedCabinetryProducts, listManagedCategories, listManagedProducts, listManagedStyleRanges, saveProduct, uploadProductImage } from '../../lib/admin-api';
import type { ProductSaveInput } from '../../lib/admin-api';
import type { ManagedCabinetryProduct, ManagedProduct, ManagedProductCategory, ManagedStyleRange } from '../../types/domain';
export function AdminProductsPage() {
  const [products, setProducts] = useState<ManagedProduct[]>([]); const [quoteBasedProducts, setQuoteBasedProducts] = useState<ManagedCabinetryProduct[]>([]); const [categories, setCategories] = useState<ManagedProductCategory[]>([]); const [styleRanges, setStyleRanges] = useState<ManagedStyleRange[]>([]); const [selected, setSelected] = useState<ManagedProduct | undefined>(); const [selectedQuoteBased, setSelectedQuoteBased] = useState<ManagedCabinetryProduct | undefined>(); const [creating, setCreating] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const [nextProducts, nextQuoteBasedProducts, nextCategories, nextRanges] = await Promise.all([listManagedProducts(), listManagedCabinetryProducts(), listManagedCategories(), listManagedStyleRanges()]); setProducts(nextProducts); setQuoteBasedProducts(nextQuoteBasedProducts); setCategories(nextCategories); setStyleRanges(nextRanges); setError(''); } catch { setError('Unable to load products.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(input: ProductSaveInput) { const saved = await saveProduct(input); if (input.imageFile) { const imagePath = await uploadProductImage(saved.id, input.imageFile); await saveProduct({ ...input, id: saved.id, imagePath, imageFile: undefined }); } await load(); setCreating(false); setSelected(undefined); }
  async function archive(product: ManagedProduct) { if (!window.confirm(`Archive ${product.name}? It will remain in previous order records.`)) return; try { await archiveProduct(product.id); await load(); if (selected?.id === product.id) setSelected(undefined); } catch { setError('Unable to archive product.'); } }
  async function remove(product: ManagedProduct) { if (!window.confirm(`Permanently delete ${product.name}? This cannot be undone.`)) return; try { await deleteProduct(product.id); await load(); if (selected?.id === product.id) setSelected(undefined); } catch (deleteError) { setError(deleteError instanceof Error ? deleteError.message : 'Unable to delete product.'); } }
  const showForm = creating || Boolean(selected);
  return <section className="admin-dashboard admin-products-page"><div className="admin-page-heading"><div><p className="eyebrow">Catalogue management</p><h1>Products</h1></div><p>Manage fixed-price and quotation-based products. Archiving preserves all past order records.</p></div><section className="admin-content-card"><div className="admin-toolbar"><div><p className="eyebrow">Priced Products</p><h2>Priced products</h2></div><button className="button" onClick={() => { setSelected(undefined); setCreating(true); }} type="button">Add priced product</button></div><p>Standard catalogue products with a fixed price and category assignment.</p><span>{products.filter((product) => product.isActive).length} visible priced products</span>{error && <p className="error" role="alert">{error}</p>}{loading ? <p className="admin-empty">Loading products…</p> : <ProductTable onArchive={(product) => void archive(product)} onDelete={(product) => void remove(product)} onEdit={(product) => { setCreating(false); setSelected(product); }} products={products} />}</section><section className="admin-content-card"><div className="admin-toolbar"><div><p className="eyebrow">Quote-Based Products</p><h2>Quote-based products</h2></div><span>{quoteBasedProducts.filter((product) => product.isActive).length} visible quote-based products</span></div><p>Made-to-measure cabinetry products. Each uses T.B.D. pricing, has no category, and requires a customer drawing before it can be added to cart.</p>{loading ? <p className="admin-empty">Loading quote-based products…</p> : <QuoteBasedProductTable onEdit={setSelectedQuoteBased} products={quoteBasedProducts} />}</section>{showForm && <AdminModal label={selected ? `Edit ${selected.name}` : 'Add priced product'} onClose={() => { setCreating(false); setSelected(undefined); }}><ProductForm categories={categories} initialValue={selected} onCancel={() => { setCreating(false); setSelected(undefined); }} onSave={save} styleRanges={styleRanges} /></AdminModal>}{selectedQuoteBased && <CabinetryProductManager onChanged={() => { void load(); }} onClose={() => setSelectedQuoteBased(undefined)} range={{ id: selectedQuoteBased.styleRangeId, slug: selectedQuoteBased.rangeSlug, name: selectedQuoteBased.rangeName }} />}</section>;
}
